# Generated by Django 4.0 on 2021-12-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='category',
            field=models.CharField(choices=[('Social', 'Social'), ('Current-Affairs', 'Current-Affairs'), ('Newspaper-cuts', 'Newspaper-cuts'), ('Travel', 'Travel'), ('Others', 'Others')], default=None, max_length=40),
        ),
    ]
